<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NativeWrapperProjectDir>$(MSBuildProjectDirectory)/../RDP.Wrapper</NativeWrapperProjectDir>
        <NativeWrapperBuildDir>$(NativeWrapperProjectDir)/build</NativeWrapperBuildDir>
        <NativeWrapperLibrary>$(NativeWrapperBuildDir)/libfreerdp_wrapper.so</NativeWrapperLibrary>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>
    <Target Name="BuildNativeWrapper" BeforeTargets="BeforeBuild">
        <Message Importance="High" Text="Building Native Wrapper..." />
        <MakeDir Directories="$(NativeWrapperBuildDir)" />
        <Exec Command="cmake -S &quot;$(NativeWrapperProjectDir)&quot; -B &quot;$(NativeWrapperBuildDir)&quot; -DCMAKE_BUILD_TYPE=$(Configuration)" />
        <Exec Command="cmake --build &quot;$(NativeWrapperBuildDir)&quot; --config $(Configuration)" />

        <ItemGroup>
            <NativeLib Include="$(NativeWrapperLibrary)" />
        </ItemGroup>
        <Copy SourceFiles="@(NativeLib)"
              DestinationFolder="$(OutputPath)"
              ContinueOnError="false" />
    </Target>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
    </ItemGroup>
</Project>
